# This CI file is based on
# https://www.r-bloggers.com/2019/02/developing-r-packages-with-usethis-and-gitlab-ci-part-iii/
image: registry.code.roche.com/beda/rocker-plus:latest
variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs/$CI_PROJECT_NAME.Rcheck"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "$R_LIBS_USER"

before_script:
  - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
  - R -e 'withr::with_libpaths(Sys.getenv("R_LIBS_USER"), if (packageVersion("remotes") < "2.3.0") remotes::install_github("r-lib/remotes", ref = "v2.3.0"))'
  - R -e 'withr::with_libpaths(Sys.getenv("R_LIBS_USER"), devtools::install_dev_deps(dep = TRUE))'

test:
  script:
  - R -e 'devtools::check(cran = FALSE, error_on = "error", check_dir = Sys.getenv("CHECK_DIR"))'

# Upload pages & devel docs
pages:
  stage: deploy
  script:
    - R -e 'withr::with_libpaths(Sys.getenv("R_LIBS_USER"), devtools::install_local())'
    - Rscript -e 'pkgdown::build_site()'
    - (cd docs && zip -r ../ci/docs.zip .)
    - 'curl -X POST --header "Docat-Api-Key: $DOCAT_API_KEY" -F "file=@ci/docs.zip" "http://docs.roche.com/api/designit/devel"'
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master

# upload versioned docs
docs:
  stage: deploy
  script:
    - "export VERSION=${CI_COMMIT_TAG#v}"
    - R -e 'withr::with_libpaths(Sys.getenv("R_LIBS_USER"), devtools::install_local())'
    - Rscript -e 'pkgdown::build_site()'
    - (cd docs && zip -r ../ci/docs.zip .)
    - "echo Version: $VERSION"
    - 'curl -X POST --header "Docat-Api-Key: $DOCAT_API_KEY" -F "file=@ci/docs.zip" "http://docs.roche.com/api/designit/$VERSION"'
    - 'curl -X PUT --header "Docat-Api-Key: $DOCAT_API_KEY" "http://docs.roche.com/api/designit/$VERSION/tags/latest"'
  only:
    - tags
