---
title: "Sample Vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Sample}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(designit)
library(tidyverse)
```

## Sample Section

This is a basic example:

```{r example1}
anno <- tribble(
  ~Cell,         ~Trt, ~Type, ~Rep,
   "WT",    "treated",   "A",    1,
   "WT",    "treated",   "A",    2,  
   "WT", "nontreated",   "A",    1,
   "WT", "nontreated",   "A",    2,
   "WT",    "control",   "A",    1,
   "WT",    "control",   "A",    2,
   "WT",    "treated",   "B",    1,
   "WT",    "treated",   "B",    2,  
   "WT", "nontreated",   "B",    1,
   "WT", "nontreated",   "B",    2,
   "WT",    "control",   "A",    1,
   "WT",    "control",   "A",    2,
   "KO",    "treated",   "A",    1,
   "KO",    "treated",   "A",    2,  
   "KO", "nontreated",   "A",    1,
   "KO", "nontreated",   "A",    2,
   "KO",    "treated",   "B",    1,
   "KO",    "treated",   "B",    2,  
   "KO", "nontreated",   "B",    1,
   "KO", "nontreated",   "B",    2,  
)
