# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  pull_request:
    branches: [main, master]  
    types: [opened]
  issue_comment:
    types: [created]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/pgkdown'
      
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        if: ${{ (steps.check.outputs.triggered == 'true') || (github.event_name != 'pull_request') && (github.event_name != 'issue_comment') }}
        shell: Rscript {0}
      
      - name: Save pkgdown artifact
        if: ${{ (steps.check.outputs.triggered == 'true') || (github.event_name != 'pull_request') && (github.event_name != 'issue_comment') }}    
        uses: actions/upload-artifact@v3
        with:
          name: pkgdown
          path: docs
          retention-days: 14

      - name: Deploy to GitHub pages 🚀
        if: ${{ (github.event_name != 'pull_request') && (github.event_name != 'issue_comment') }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
          single-commit: true
